### ISSUE TITLE
Error compiling on Linux Ubuntu CleanUnitOnMemFailed not declared in this scope

### ISSUE THREAD

**Issue by jreus** [elgiano/nn.ar#5]
I've been struggling to compile from source. Getting the following error where ClearUnitOnMemFailed cannot be found. Where should this be located?
Thanks!

```
/home/Dev/nn-supercollider/plugins/NNModel/cpp/NNUGens.cpp: In constructor ‘NN::NNUGen::NNUGen()’:
/home/Dev/nn-supercollider/plugins/NNModel/cpp/NNUGens.cpp:261:5: error: ‘ClearUnitOnMemFailed’ was not declared in this scope
  261 |     ClearUnitOnMemFailed;
      |     ^~~~~~~~~~~~~~~~~~~~
/home/Dev/nn-supercollider/plugins/NNModel/cpp/NNUGens.cpp:269:5: error: ‘ClearUnitOnMemFailed’ was not declared in this scope
  269 |     ClearUnitOnMemFailed;
      |     ^~~~~~~~~~~~~~~~~~~~
gmake[2]: *** [CMakeFiles/NNUGens_scsynth.dir/build.make:76: CMakeFiles/NNUGens_scsynth.dir/plugins/NNModel/cpp/NNUGens.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:85: CMakeFiles/NNUGens_scsynth.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2

```

**Comment by elgiano** [comment]
It should be in supercollider sources, more precisely in `include/plugin_interface/SC_Unit.h`. Which version of supercollider sources are you using? This macro is in both latest main and develop, it was merged in version 3.13 as part of a PR to fix some memory allocation errors and mainly remove exception throwing from the main DSP loop.

I should add to the README that sc 3.13 is required. If for any reason you can't compile with sc 3.13, you can define the macro yourself, here is the source:

https://github.com/supercollider/supercollider/blob/a80436ac2cb22b8cef62192c86be2951639c184f/include/plugin_interface/SC_Unit.h#L83-L92

**Comment by elgiano** [comment]
@jreus how is it going? did you manage to build from source in the end?
